#서버 포트 8000 , path는 기본 / 
server:
  port: 8000
  servlet:
    context-path: /

spring:
  #어플리 케이션 이름 설정
  application:
    name: springboot
  #뷰 디렉토리 및 확장자는 jsp를 사용
  mvc:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  #encoding 설정 (utf8)
  http.encoding:
    charset: utf-8
    enabled: true
    force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://34.64.212.229:3306/OBOT_DEV?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Azaz!154646
  jpa: 
    show-sql: true